"""DECISIONS.md — the register that did not exist.

Decision numbers were spent twice in four days (the 21 September DC set and the
25 September national set both took D-78 through D-81) and five were invented
without checking on 18 September, because D-## numbers live scattered across
MANIFEST_SESSION.md and half a dozen documents with no index. standing_index.py
already solves this for S-## notes; this is the same instrument for decisions.

Generated. Do not hand-edit: change the manifest and re-run.
"""
import re, pathlib, sys, collections

SRC = pathlib.Path("MANIFEST_SESSION.md")
OUT = pathlib.Path("DECISIONS.md")

# A decision heading: bold or plain, at a line start, "D-nn" then a separator
# and a title. Bodies are not captured; this is an index, not a copy.
PAT = re.compile(r'^(?:[-*+]\s+)?\**\s*D-(\d+)\s*[.\u00b7:\u2013\u2014-]\s*(.+)$')
DATE = re.compile(r'^#+\s.*?(\d{4}-\d{2}-\d{2})')


def clean(t):
    t = t.replace("**", "").strip()
    # The heading is the first sentence; the body follows on the same line.
    m = re.match(r'(.+?[.?!])(?:\s|$)', t)
    return (m.group(1) if m else t).rstrip(". ").strip()


def scan():
    rows, date = [], "undated"
    for n, line in enumerate(SRC.read_text().split("\n"), 1):
        m = DATE.match(line)
        if m:
            date = m.group(1)
            continue
        m = PAT.match(line.strip())
        if m:
            title = clean(m.group(2))
            if len(title) > 8:
                rows.append((int(m.group(1)), date, title))
    return rows


def main():
    rows = scan()
    seen = collections.defaultdict(list)
    for num, date, title in rows:
        if (date, title) not in seen[num]:
            seen[num].append((date, title))
    lines = ["# Decisions", "",
             "Generated by `decisions_index.py` from `MANIFEST_SESSION.md`.",
             "Check the highest number here BEFORE allocating a new one.", ""]
    dupes = {k: v for k, v in seen.items() if len(v) > 1}
    if dupes:
        lines += ["## Collisions", "",
                  "A number used more than once. Resolve before it propagates.", ""]
        for k in sorted(dupes):
            for date, title in dupes[k]:
                lines.append(f"- **D-{k:02d}** ({date}) {title}")
        lines.append("")
    gaps = [n for n in range(1, max(seen)) if n not in seen]
    lines += [f"Highest allocated: **D-{max(seen):02d}**. "
              f"Next free: **D-{max(seen)+1:02d}**.", ""]
    if gaps:
        lines += [f"**Coverage is partial: {len(seen)} of {max(seen)} numbers found.** "
                  "The rest were recorded in formats this parser does not match, or "
                  "in documents other than the manifest. Missing: "
                  + ", ".join(f"D-{n:02d}" for n in gaps) + ".", "",
                  "Backfilling them is an open item. Until it is done, allocate from "
                  "the highest number above and never from a gap.", ""]
    lines += ["## Register", ""]
    for k in sorted(seen):
        for date, title in seen[k]:
            lines.append(f"- **D-{k:02d}** · {date} · {title}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} — {len(seen)} decisions, highest D-{max(seen):02d}, "
          f"{len(dupes)} collision(s)")
    return 1 if dupes else 0


if __name__ == "__main__":
    sys.exit(main())
