"""
html2typst.py — port the manuscript from the HTML template to Typst.

    python3 html2typst.py paper_national_v3.html paper_national.typ

Written as a converter rather than a retype so the state editions inherit it and
so the port is reversible: the HTML stays the source of record until the Typst
output has been compared against it.

The point of the move is float placement. A column figure becomes a float scoped
to its column and a spanning figure a float scoped to the page, and the engine
decides where they sit instead of the author guessing and sweeping heights.
"""
import html as ihtml
import re
import sys

from bs4 import BeautifulSoup

COVER = r"""
#block(height: 181mm)[
  #grid(columns: (1.06fr, 1fr), gutter: 16mm, align: horizon,
    [
      #line(length: 52mm, stroke: 6pt + blue)
      #v(8mm)
      #text(font: "Jost", size: 40pt, weight: 600, fill: blue)[%(title)s]
      #v(4mm)
      #text(size: 14pt, weight: 300)[%(sub)s]
      #v(10mm)
      #text(font: "Jost", size: 11.5pt, weight: 500)[%(by)s] \\
      #text(font: "Jost", size: 9.5pt, weight: 300, fill: mut)[Agilian LLC]
    ],
    [
      #image("%(img)s", width: 100%%)
      #v(4mm) #line(length: 100%%, stroke: 0.5pt + rule) #v(3mm)
      #set par(justify: false)
      #text(size: 8pt, fill: mut)[%(stamp)s]
    ])
]
#pagebreak()
"""

PREAMBLE = r'''// Generated by html2typst.py. Edit the HTML or this generator, not this file.
#set page(
  width: 11in, height: 8.5in,
  margin: (x: 15mm, top: 14mm, bottom: 13mm),
)
// Columns as a page property rather than a show rule: a show rule wraps the whole
// document in a container, and Typst forbids pagebreaks inside containers.

#let blue = rgb("#17325c")
#let ink = rgb("#272727")
#let mut = rgb("#6f6f6f")
#let paper = rgb("#faf8f3")
#let rule = rgb("#e2dccf")
#let loss = rgb("#8B5A5A")

#set text(font: "Nunito", size: 9.7pt, fill: ink, lang: "en", region: "us")
#set par(justify: true, leading: 0.62em, spacing: 0.9em)
#show strong: set text(weight: 800, fill: blue)

#let sechead(title) = [
  #place(top, scope: "parent", float: true, clearance: 5mm, block(width: 100%)[
    #text(font: "Jost", size: 21pt, weight: 600, fill: blue)[#title]
    #v(2.5mm)
    #line(length: 100%, stroke: 2pt + blue)
  ])
]
#let plate(title, img, cap) = [
  #text(font: "Jost", size: 17pt, weight: 600, fill: blue)[#title]
  #v(2.5mm)
  #line(length: 100%, stroke: 2pt + blue)
  #v(4mm)
  #align(center, image(img, height: 126mm))
  #v(2mm)
  #line(length: 100%, stroke: 0.5pt + rule)
  #v(1.4mm)
  #text(size: 8.6pt, fill: mut)[#cap]
]
#let h3(t) = block(above: 4.5mm, below: 1.5mm, sticky: true,
  text(font: "Jost", size: 11.4pt, weight: 600, fill: blue)[#t])
#let lede(t) = block(below: 3mm, text(size: 10.8pt, weight: 300)[#t])
#let cap(t) = block[
  #v(1.8mm) #line(length: 100%, stroke: 0.5pt + rule) #v(1.4mm)
  #set par(justify: false, leading: 0.5em)
  #text(size: 7.9pt, fill: mut)[#t]
]
// A column figure floats to the top of its column; a wide one to the top of the
// page. The engine places it. Nothing here guesses a height to make it fit.
#let colfig(img, c, h: 87.2mm) = place(top, scope: "column", float: true,
  clearance: 5mm, block(width: 100%)[#align(center, image(img, height: h)) #cap(c)])
#let widefig(img, c, h: 60mm) = place(top, scope: "parent", float: true,
  clearance: 6mm, block(width: 100%)[#align(center, image(img, height: h)) #cap(c)])
#let boxed(body) = block(width: 100%, fill: paper, inset: (x: 5.5mm, y: 4.5mm),
  stroke: (left: 5pt + blue, rest: 0.5pt + rule), below: 6mm)[
  #set text(size: 9.2pt)
  #body
]
#let flagged(body) = block(width: 100%, fill: paper, inset: (x: 4mm, y: 3.5mm),
  stroke: (dash: "dashed", paint: loss, thickness: 0.5pt), below: 6mm)[
  #set text(size: 8.9pt)
  #body
]
'''


def inline(node):
    """Inline HTML to Typst markup."""
    out = []
    for c in node.children:
        if isinstance(c, str):
            t = ihtml.unescape(c)
            t = re.sub(r"\s+", " ", t)
            # backslash first: escaping it last re-escapes the backslashes the
            # earlier passes just added, and "\$100" becomes "\\$100"
            for ch in ("\\", "#", "$", "@", "*", "_", "<", ">"):
                t = t.replace(ch, "\\" + ch)
            out.append(t)
        elif c.name == "strong":
            out.append("*" + inline(c).strip() + "*")
        elif c.name == "b":
            out.append("*" + inline(c).strip() + "*")
        elif c.name == "em":
            out.append("_" + inline(c).strip() + "_")
        elif c.name == "sup":
            out.append("#super[" + inline(c).strip() + "]")
        elif c.name == "br":
            out.append(" \\ ")
        else:
            out.append(inline(c))
    return "".join(out)


def table(tag):
    rows = tag.find_all("tr")
    head = rows[0]
    ncol = len(head.find_all(["th", "td"]))
    aligns = []
    for cell in head.find_all(["th", "td"]):
        aligns.append("right" if "n" in (cell.get("class") or []) else "left")
    lines = ["#block(below: 3.5mm, table(",
             "  columns: %d," % ncol,
             "  align: (%s)," % ", ".join(aligns),
             "  stroke: (x, y) => (bottom: if y == 0 { 1.5pt + blue } "
             "else { 0.5pt + rule }),",
             "  inset: (x: 1.6mm, y: 1.3mm),"]
    for i, r in enumerate(rows):
        cells = r.find_all(["th", "td"])
        vals = []
        for cell in cells:
            txt = inline(cell).strip()
            cls = cell.get("class") or []
            if cell.name == "th":
                txt = ("#text(font: \"Jost\", size: 7.7pt, weight: 600, fill: mut)"
                       "[#upper[%s]]" % txt)
            elif "svc" in cls:
                txt = "#text(weight: 700, fill: blue)[%s]" % txt
            if "tot" in (r.get("class") or []):
                txt = "#text(weight: 800, fill: blue)[%s]" % txt
            vals.append("[" + txt + "]")
        lines.append("  " + ", ".join(vals) + ",")
    lines.append("))")
    return "\n".join(lines)


def figure(tag):
    img = tag.find("img")["src"]
    capt = inline(tag.find("figcaption")).strip()
    cls = tag.get("class") or []
    if "span" in cls:
        return '#widefig("%s", [%s])' % (img, capt)
    h = {"portrait": "87.2mm", "wide": "61.6mm", "squeeze": "66.7mm"}.get(
        next((c for c in cls if c in ("portrait", "wide", "squeeze")), ""), "87.2mm")
    return '#colfig("%s", [%s], h: %s)' % (img, capt, h)


def convert(path_in, path_out):
    soup = BeautifulSoup(open(path_in).read(), "html.parser")
    out = [PREAMBLE]
    cov = soup.find("div", class_="cover")
    if cov:
        out.append(COVER % dict(
            title="\\$100 Medicaid \\ Dollars",
            sub=inline(cov.find("h2")).strip(),
            by=inline(cov.find("div", class_="by")).strip().split("Agilian")[0].strip(),
            img=cov.find("img")["src"],
            stamp=inline(cov.find("div", class_="stamp")).strip()))
    body_started = False

    for el in soup.find_all(["div", "figure", "table", "p", "h3"], recursive=True):
        cls = el.get("class") or []
        if el.find_parent("figure") or el.find_parent("table"):
            continue
        if "cover" in cls:
            continue
        if "sechead" in cls:
            title = inline(el.find("h2")).strip()
            if not body_started:
                out.append("#set page(columns: 2)")
                body_started = True
            out.append("#sechead[%s]" % title)
        elif "plate" in cls:
            fig = el.find("figure")
            title = inline(el.find("h2")).strip() if el.find("h2") else ""
            out.append("#pagebreak(weak: true)\n#set page(columns: 1)")
            out.append('#plate([%s], "%s", [%s])'
                       % (title, fig.find("img")["src"],
                          inline(fig.find("figcaption")).strip()))
            out.append("#pagebreak(weak: true)\n#set page(columns: 2)")
        elif "authgrid" in cls:
            bios = []
            for b in el.find_all("div", class_="bio"):
                nm = inline(b.find("div", class_="nm")).strip()
                rl = inline(b.find("div", class_="rl")).strip()
                txt = []
                for c in b.children:
                    if getattr(c, "name", None) in ("div",):
                        continue
                    txt.append(inline(c) if getattr(c, "name", None) else
                               re.sub(r"\s+", " ", ihtml.unescape(str(c))))
                body = "".join(txt).strip()
                for ch in ("\\", "#", "$", "@", "*", "_", "<", ">"):
                    body = body.replace(ch, "\\" + ch)
                bios.append('[#text(font: "Jost", size: 11pt, weight: 600, fill: blue)[%s] \\\n'
                            '#text(font: "Jost", size: 8.6pt, fill: mut)[%s]\n\n'
                            '#set text(size: 8.8pt)\n%s]' % (nm, rl, body))
            out.append("#grid(columns: (1fr, 1fr), gutter: 11mm,\n  "
                       + ",\n  ".join(bios) + ")")
        elif "disclose" in cls:
            out.append('#block(above: 3mm)[\n'
                       '#line(length: 100%, stroke: 0.5pt + rule)\n'
                       '#v(2mm)\n'
                       '#set par(justify: false)\n'
                       '#text(size: 8pt, fill: mut)[' + inline(el).strip() + ']\n]')
        elif "box" in cls:
            inner = "\n\n".join(inline(p).strip() for p in el.find_all("p"))
            out.append("#boxed[%s]" % inner)
        elif "flag" in cls:
            inner = "\n\n".join(inline(p).strip() for p in el.find_all("p"))
            out.append("#flagged[%s]" % inner)
        elif el.name == "figure":
            out.append(figure(el))
        elif el.name == "table":
            out.append(table(el))
        elif el.name == "h3":
            if el.find_parent("div", class_=["box", "flag"]):
                continue
            out.append("#h3[%s]" % inline(el).strip())
        elif el.name == "p" and not el.find_parent(
                ["div"], class_=["box", "flag", "authgrid", "bio"]):
            txt = inline(el).strip()
            if not txt:
                continue
            if "lede" in cls:
                out.append("#lede[%s]" % txt)
            else:
                out.append(txt)

    open(path_out, "w").write("\n\n".join(out) + "\n")
    print("wrote", path_out, len(out), "blocks")


if __name__ == "__main__":
    convert(sys.argv[1] if len(sys.argv) > 1 else "paper_national_v3.html",
            sys.argv[2] if len(sys.argv) > 2 else "paper_national.typ")
