#!/usr/bin/env python3
"""standing_index.py — regenerate STANDING_INDEX.md from the standing notes.

`EDITORIAL_STANDING_NOTES.md` is append-only and correctly so: it is the
record, and the record does not get rewritten. But it is now over 1,200 lines,
and reading it in full at the start of every session costs more than it
returns, because most of any given session touches five or six of the hundred
notes.

So the record stays append-only and this generates a one-line-per-note index
beside it. A session reads the index, then opens the full note for the handful
that bear on the work in front of it. Generated rather than maintained, so it
cannot drift from the notes it indexes — which is the same reason the endnote
register generates from the ledger.

    python3 standing_index.py           write STANDING_INDEX.md
    python3 standing_index.py --check   fail if it is out of date
"""
import re
import sys
from pathlib import Path

SRC = Path("EDITORIAL_STANDING_NOTES.md")
OUT = Path("STANDING_INDEX.md")
# Headings wrap onto a second line often enough that a line-anchored pattern
# silently dropped thirteen of a hundred notes — an index with holes in it is
# worse than no index, because it reads as complete.
HEAD = re.compile(
    r"^\*\*(S-\d+)\s*·\s*(?:([A-Z][A-Za-z ]{2,22}?)\s*·\s*)?(.+?)\*\*",
    re.M | re.S)


def build() -> str:
    text = SRC.read_text()
    rows = [(m.group(1), (m.group(2) or "").strip(), m.group(3).strip())
            for m in HEAD.finditer(text)]
    seen, out = set(), []
    for n, role, title in rows:
        if n in seen:
            continue
        seen.add(n)
        out.append((n, role, " ".join(title.split()).rstrip(".")))
    by_role = {}
    for n, role, title in out:
        by_role.setdefault(role or "Unfiled", []).append((n, title))

    L = [f"# Standing notes — index ({len(out)} notes)",
         "",
         "Generated by `standing_index.py`. Do not edit; edit",
         "`EDITORIAL_STANDING_NOTES.md` and regenerate.",
         "",
         "Read this at session start. Open the full note in",
         "`EDITORIAL_STANDING_NOTES.md` for the ones that bear on the work in",
         "front of you — the one-liner is a pointer, never the authority.",
         ""]
    for role in sorted(by_role, key=lambda r: (r == "Unfiled", r)):
        L.append(f"## {role}")
        L.append("")
        for n, title in by_role[role]:
            L.append(f"- **{n}** — {title}")
        L.append("")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    new = build()
    if "--check" in sys.argv:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur != new:
            print("STANDING_INDEX.md is out of date. Run: python3 standing_index.py")
            sys.exit(1)
        print("STANDING_INDEX.md current")
    else:
        OUT.write_text(new)
        print(f"wrote {OUT} — {new.count(chr(10) + '- ')} notes indexed")
